# Generated by Django 5.1.2 on 2024-10-24 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_app', '0003_loginprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginProfile',
            new_name='LoginTable',
        ),
    ]
