# Generated by Django 5.1.2 on 2024-10-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_app', '0004_rename_loginprofile_logintable'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintable',
            name='type',
            field=models.CharField(default=4, max_length=200),
            preserve_default=False,
        ),
    ]
