# Generated by Django 5.1.2 on 2024-10-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_app', '0005_logintable_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodels',
            name='quantity',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
