# Generated by Django 5.1.2 on 2024-10-30 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('static_app', '0006_usersmodels_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='static_app.usersmodels')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='static_app.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='static_app.usersmodels')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.cart')),
            ],
        ),
    ]
